


CREATE TABLE FTP_SERVER (
  ID IDENTITY AUTO_INCREMENT NOT NULL,
  IP_ADDRESS VARCHAR NOT NULL,
  PORT INT NOT NULL ,
  PRIMARY KEY (ID)
);
INSERT INTO FTP_SERVER ( IP_ADDRESS, PORT) VALUES ( '127.0.0.1', 54394) ;
INSERT INTO FTP_SERVER ( IP_ADDRESS, PORT) VALUES ( '127.0.0.1', 54394) ;
INSERT INTO FTP_SERVER ( IP_ADDRESS, PORT) VALUES ( '127.0.0.1', 54394) ;


ALTER TABLE FTP_USER ADD COLUMN ID IDENTITY NOT NULL;
ALTER TABLE FTP_USER ADD COLUMN FTP_SERVER_ID BIGINT NOT NULL  DEFAULT 1 ;
ALTER TABLE FTP_USER ADD FOREIGN KEY (FTP_SERVER_ID) REFERENCES FTP_SERVER(ID);

